#!/usr/bin/env python3

import sys
import os
import time

try:
	import requests
except:
	print('requests library not found')
	for sdf in range(3,0,-1):
		sys.stdout.write('Installing library in %s\r' % sdf)
		sys.stdout.flush()
		time.sleep(1)
	try:
		os.system('pip3 install requests')
	except:
		print('installtion error check internet connection')
finally:
	import requests
		
try:
	from bs4 import BeautifulSoup
except:
	print('bs4 library not found')
	for sdf in range(3,0,-1):
		sys.stdout.write('Installing library in %s\r' % sdf)
		sys.stdout.flush()
	try:
		os.system('pip3 install beautifulsoup4')
	except:
		print('installtion error check internet connection')
finally:
	from bs4 import BeautifulSoup

def cunt():
	billy = ''' <a href='https://www.symptoma.es/'>https://www.symptoma.es/</a> <script type='text/javascript' src='https://www.freevisitorcounters.com/auth.php?id=7ada45dff3629d875092bed977daf886f09027c8'></script>
	<script type="text/javascript" src="https://www.freevisitorcounters.com/en/home/counter/653335/t/2"></script>'''
	link = r'https://www.worldometers.info/coronavirus/'
	text = requests.get(link).text
	source = BeautifulSoup(text,features='html.parser')
	lIst = []
	List = []
	for i in source.find_all('div',class_='main_table_countries_div'):
		print('Country\t\tCases\t\tNew Cases\tTotal Deaths')
		lIst.append(i)
		for j in i.find_all('tr'):
			count = 0
			
			print('--------------------------------------------------------------------------')
			for k in j.find_all('td'):
				if count <= 3:
					asd = k.text.strip(' ')
					if asd == '':
						asd = 'NULL'
						#print(asd)
					tab = '\t'
					if len(asd) > 5:
						if len(asd) > 10:
							asd = asd[0:7]
						print('|'+ asd +'|'+tab,end='')
					else:
						print('|'+ asd +'|'+tab*2,end='')
					List.append(asd)
					count+=1
					
				else:
					count = 0
					break		
			print('')
		
		break
	try:
		file = open('index.html','w+')
		file.close()
		file = open('index.html','a+')
		for i in lIst:
			i = str(i)
			file.write(i)
			
		file.write(billy)
		file.close()
		os.system('ssh-add /home/lawlie8/github1')
		os.system('git add -A && git commit -m "update"')
		os.system('git push')
	except:
		sys.stdout.write('error at file upload')
cunt()
